# import

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib
matplotlib.rcParams['font.family'] = "serif"
file_path ='/Users/liu/Desktop/Pitts/Project/data/R3_1971_YE_ENCOUNTER_NOTES_2021_03_05/R3_1971_YE_DIAGNOSES_2021_03_01.csv'

In [4]:
DIAGNOSES = pd.read_csv(file_path,encoding = "ISO-8859-1",low_memory=False)
DIAGNOSES['DX_FROM_DATE'] = pd.to_datetime(DIAGNOSES['DX_FROM_DATE'], format='%m/%d/%Y')
DIAGNOSES['DX_TO_DATE'] = pd.to_datetime(DIAGNOSES['DX_TO_DATE'], format='%m/%d/%Y')
DIAGNOSES.head(20)

,STUDY_ID,DIAGNOSIS_TYPE,DX_CODE,DIAGNOSIS_NAME,PRIMARY_DX_IND,DX_FROM_DATE,DX_TO_DATE
0,5225357772,ICD9CM,011.90,"Pulmonary tuberculosis, unspecified, unspecified",N,2011-03-17,2011-03-20
1,5225567678,ICD9CM,013.00,"Tuberculous meningitis, unspecified",Y,2014-11-08,2014-11-15
2,5225563315,ICD9CM,013.20,"Tuberculoma of brain, unspecified",N,2014-03-28,2014-04-17
3,5220332708,ICD9CM,027.0,Listeriosis,Y,2015-01-18,2015-01-24
4,5220165181,ICD9CM,027.0,Listeriosis,Y,2014-12-19,2015-01-09
5,5225172338,ICD9CM,016.50,"Tuberculosis of other male genital organs, uns...",N,2012-12-30,2013-01-02
6,5220427063,ICD9CM,002.0,Typhoid fever,Y,2011-09-13,2011-09-21
7,5225658053,ICD9CM,003.0,Salmonella gastroenteritis,Y,2013-03-15,2013-03-16
8,5220138989,ICD9CM,003.0,Salmonella gastroenteritis,N,2014-12-25,2015-01-01
9,5222875420,ICD9CM,003.1,Salmonella septicemia,Y,2012-01-20,2012-01-25
10,5220177792,ICD9CM,003.1,Salmonella septicemia,Y,2014-12-15,2014-12-19
11,5220138989,ICD9CM,003.21,Salmonella meningitis,Y,2015-01-01,2015-01-05
12,5220138989,ICD9CM,003.21,Salmonella meningitis,Y,2014-12-25,2015-01-01
13,5222170334,ICD9CM,005.89,Other bacterial food poisoning,Y,2014-01-15,2014-01-19
14,5222707319,ICD9CM,005.9,"Food poisoning, unspecified",Y,2013-01-12,2013-01-14
15,5225604739,ICD9CM,005.9,"Food poisoning, unspecified",N,2013-04-11,2013-04-11
16,5222195798,ICD9CM,005.9,"Food poisoning, unspecified",N,2015-01-12,2015-01-13
17,5222770859,ICD9CM,005.9,"Food poisoning, unspecified",N,2011-11-14,2011-11-18
18,5222174028,ICD9CM,007.1,Giardiasis,N,2012-11-18,2012-11-25
19,5225034058,ICD9CM,007.4,Cryptosporidiosis,Y,2012-04-28,2012-05-12

In [3]:
DIAGNOSES.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1826776 entries, 0 to 1826775
Data columns (total 7 columns):
 #   Column          Dtype
---  ------          -----
 0   STUDY_ID        int64
 1   DIAGNOSIS_TYPE  object
 2   DX_CODE         object
 3   DIAGNOSIS_NAME  object
 4   PRIMARY_DX_IND  object
 5   DX_FROM_DATE    datetime64[ns]
 6   DX_TO_DATE      datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(4)
memory usage: 97.6+ MB

In [4]:
DIAGNOSES.describe(include='all')

/var/folders/pp/qtk1lyns6zg8x9dlj6f5xvtm0000gn/T/ipykernel_28291/3173427475.py:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  DIAGNOSES.describe(include='all')

,STUDY_ID,DIAGNOSIS_TYPE,DX_CODE,DIAGNOSIS_NAME,PRIMARY_DX_IND,DX_FROM_DATE,DX_TO_DATE
count,1.826776e+06,1806026,1826776,1806026,1826776,1826776,1686455
unique,NaN,4,16794,16239,2,3551,3536
top,NaN,ICD10CM,I10,Essential (primary) hypertension,N,2020-11-30 00:00:00,2020-12-22 00:00:00
freq,NaN,1658177,38051,38051,1603246,6115,5727
first,NaN,NaN,NaN,NaN,NaN,2011-01-01 00:00:00,2011-01-01 00:00:00
last,NaN,NaN,NaN,NaN,NaN,2021-01-31 00:00:00,2021-02-16 00:00:00
mean,5.223123e+09,NaN,NaN,NaN,NaN,NaN,NaN
std,1.758561e+06,NaN,NaN,NaN,NaN,NaN,NaN
min,5.220000e+09,NaN,NaN,NaN,NaN,NaN,NaN
25%,5.222196e+09,NaN,NaN,NaN,NaN,NaN,NaN
50%,5.222728e+09,NaN,NaN,NaN,NaN,NaN,NaN
75%,5.225112e+09,NaN,NaN,NaN,NaN,NaN,NaN
max,5.229273e+09,NaN,NaN,NaN,NaN,NaN,NaN

# PRIMARY_DX_IND

In [9]:
DIAGNOSES.PRIMARY_DX_IND.value_counts()*100/DIAGNOSES.PRIMARY_DX_IND.shape[0]

N    87.763689
Y    12.236311
Name: PRIMARY_DX_IND, dtype: float64

# DX_CODE

In [18]:
(DIAGNOSES.DX_CODE.isin(covid)).sum()*100/DIAGNOSES.shape[0]

0.9470236088058963

In [8]:
covid = ['U07.1', 'Z11.52', 'Z20.822', 'J12.82']

In [19]:
covid_record = DIAGNOSES[DIAGNOSES.DX_CODE.isin(covid)]

In [20]:
covid_record

,STUDY_ID,DIAGNOSIS_TYPE,DX_CODE,DIAGNOSIS_NAME,PRIMARY_DX_IND,DX_FROM_DATE,DX_TO_DATE
1805092,5222332886,ICD10,U07.1,COVID-19,Y,2020-07-06,NaT
1805093,5220589908,ICD10,U07.1,COVID-19,Y,2020-07-06,NaT
1805094,5220055723,ICD10,U07.1,COVID-19,N,2020-07-08,NaT
1805095,5225508479,ICD10,U07.1,COVID-19,N,2020-07-08,NaT
1805096,5222867644,ICD10,U07.1,COVID-19,Y,2020-07-08,NaT
...,...,...,...,...,...,...,...
1826770,5222342265,NaN,Z20.822,NaN,N,2021-01-07,2021-01-09
1826771,5222512326,NaN,Z20.822,NaN,N,2021-01-13,2021-01-14
1826772,5222171889,NaN,Z20.822,NaN,N,2021-01-18,2021-01-18
1826773,5222589229,NaN,Z20.822,NaN,N,2021-01-13,2021-01-20
1826774,5222497492,NaN,Z20.822,NaN,N,2021-01-26,2021-01-26

In [22]:
covid_record.to_csv('covid_record.csv', index = False)